version: 2
jobs:
  publish:
    working_directory: ~/repo
    docker:
      - image: circleci/node:15.14
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: yarn install
      - run: yarn lint
      - run: yarn test
      - run: yarn build
      - run: npm publish --access=public
  build:
    docker:
      - image: circleci/node:15.14
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - run: yarn lint
      - run: yarn test:coverage
      - run: yarn build
      - run:
          name: Install Code Climate reporter
          command: |
            if [[ ! -x cc-test-reporter ]]
            then
              curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
              chmod +x ./cc-test-reporter
            fi
      - run:
          name: Report code coverage to Code Climate
          command: |
            ./cc-test-reporter after-build -t lcov --exit-code $? || true
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
workflows:
  version: 2
  tagged-build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
